export {default as Home} from './Home'
export {default as Todos} from './Todos'
export {default as Login} from './Login'
export {default as SingleTodo} from './SingleTodo'
export {default as CreateTodo} from './createTodo'
export {default as NavBar} from './Navbar'